# Generated by Django 4.2.2 on 2023-07-11 08:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=50)),
                ('company_name', models.TextField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_discribtion', models.TextField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients_count', models.PositiveIntegerField()),
                ('happy_clients_description', models.TextField(blank=True, max_length=250, null=True)),
                ('projects_count', models.PositiveIntegerField()),
                ('projects_description', models.TextField(blank=True, max_length=250, null=True)),
                ('awards_count', models.PositiveIntegerField()),
                ('awards_description', models.TextField(blank=True, max_length=250, null=True)),
                ('coffee_cup_count', models.PositiveIntegerField()),
                ('coffee_cup_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('city', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=20)),
                ('freelance', models.CharField(max_length=20)),
                ('github', models.URLField(validators=[django.core.validators.URLValidator])),
                ('sumary_name', models.CharField(max_length=30)),
                ('sumary_description', models.TextField(max_length=300)),
                ('about', models.TextField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service_description', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('link_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_position', models.CharField(max_length=50)),
                ('opinion', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
